(* TODO: Add more chars, caret, and escape *)

letter = "A-Z" | "a-z" ;

digit = "0-9" ;

char = letter | digit | "_" ;

eol = "\n" | "\r\n" ;

comment = "! ", { char }, { " " }, eol ;

indented_comment =  "  ", comment ;

key = "~ ", char, { char }, { " " }, eol ;

lang = "  ", char, { char }, ":" ;

single_line_trans = lang, char, { char }, { " " }, eol ;

multi_line_trans = "    ", { char }, { " " }, eol ;

hard_multi_line_trans = lang, " [", { multi_line_trans }, "  ]", { " " }, eol ;

soft_multi_line_trans = lang, " (", { multi_line_trans }, "  )", { " " }, eol ;

trans = single_line_trans | hard_multi_line_trans | soft_multi_line_trans ;

section = { comment }, key, { indented_comment }, trans, { indented_comment }, eol, eol ;

trans_file = { eol }, section, { section } ;